#Infra ci
name: GCP INFRA DEPLOY (Terraform)

on:
  push:
    branches: [main]

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Check creds
        run: |
          echo "Checking GOOGLE_APPLICATION_CREDENTIALS file"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS
          cat $GOOGLE_APPLICATION_CREDENTIALS | head -n 5
          gcloud auth list


      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.6.6

      # - name: Terraform Init & Apply
      #   working-directory: ./environments/dev
      #   run: |
      #     terraform init
      #     terraform apply -auto-approve
           
